// <auto-generated />
using System;
using System.Collections;
using Data.SchemaMigrator.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Data.SchemaMigrator.Migrations
{
    [DbContext(typeof(PlasticoDbContext))]
    [Migration("20220522165813_initSchema")]
    partial class initSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:PostgresExtension:pg_buffercache", ",,")
                .HasAnnotation("Npgsql:PostgresExtension:pg_stat_statements", ",,")
                .HasAnnotation("Npgsql:PostgresExtension:pgcrypto", ",,")
                // .HasAnnotation("Npgsql:PostgresExtension:pgrouting", ",,")
                .HasAnnotation("Npgsql:PostgresExtension:postgis", ",,")
                .HasAnnotation("Npgsql:PostgresExtension:postgis_topology", ",,")
                .HasAnnotation("Npgsql:PostgresExtension:uuid-ossp", ",,")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Data.SchemaMigrator.Models.AiModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("Createdon")
                        .HasColumnName("createdon")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Version")
                        .HasColumnName("version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("model","campaign");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Bi_Log", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnName("campaign_id")
                        .HasColumnType("uuid");

                    b.Property<double?>("ElapsedTime")
                        .HasColumnName("elapsed_time")
                        .HasColumnType("double precision");

                    b.Property<string>("FailedStep")
                        .HasColumnName("failed_step")
                        .HasColumnType("text");

                    b.Property<DateTime>("FinishedOn")
                        .HasColumnName("finished_on")
                        .HasColumnType("date");

                    b.Property<DateTime>("InitiatedOn")
                        .HasColumnName("initiated_on")
                        .HasColumnType("date");

                    b.Property<string>("Reason")
                        .HasColumnName("reason")
                        .HasColumnType("text");

                    b.Property<string>("ScriptVersion")
                        .HasColumnName("script_version")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("status")
                        .HasColumnType("text")
                        .HasDefaultValue("HARD_FAIL");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId")
                        .HasName("IX_bi_campaign_id");

                    b.ToTable("bi","logs");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.BoundingBoxes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("createdon")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Height")
                        .HasColumnName("height")
                        .HasColumnType("integer");

                    b.Property<Guid>("IdCreatorFk")
                        .HasColumnName("id_creator_fk")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdRefImagesForLabelling")
                        .HasColumnName("id_ref_images_for_labelling")
                        .HasColumnType("uuid");

                    b.Property<int>("IdRefTrashTypeFk")
                        .HasColumnName("id_ref_trash_type_fk")
                        .HasColumnType("integer");

                    b.Property<int>("LocationX")
                        .HasColumnName("location_x")
                        .HasColumnType("integer");

                    b.Property<int>("LocationY")
                        .HasColumnName("location_y")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnName("width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdCreatorFk")
                        .HasName("IX_bounding_boxes_IdCreatorFk");

                    b.HasIndex("IdRefImagesForLabelling");

                    b.HasIndex("IdRefTrashTypeFk")
                        .HasName("IX_bounding_boxes_IdRefTrashTypeFk");

                    b.ToTable("bounding_boxes","label");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Campaign_Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("Createdon")
                        .HasColumnName("createdon")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("IdRefModelFk")
                        .HasColumnName("id_ref_model_fk")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdRefUserFk")
                        .HasColumnName("id_ref_user_fk")
                        .HasColumnType("uuid");

                    b.Property<bool?>("Isaidriven")
                        .HasColumnName("isaidriven")
                        .HasColumnType("boolean");

                    b.Property<string>("Locomotion")
                        .IsRequired()
                        .HasColumnName("locomotion")
                        .HasColumnType("text");

                    b.Property<string>("Remark")
                        .HasColumnName("remark")
                        .HasColumnType("text");

                    b.Property<string>("Riverside")
                        .HasColumnName("riverside")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasName("campaign_id");

                    b.HasIndex("IdRefModelFk");

                    b.HasIndex("IdRefUserFk");

                    b.ToTable("campaign","campaign");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Etl_Log", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnName("campaign_id")
                        .HasColumnType("uuid");

                    b.Property<double?>("ElapsedTime")
                        .HasColumnName("elapsed_time")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("FinishedOn")
                        .HasColumnName("finished_on")
                        .HasColumnType("date");

                    b.Property<DateTime>("InitiatedOn")
                        .HasColumnName("initiated_on")
                        .HasColumnType("date");

                    b.Property<Guid>("MediaId")
                        .HasColumnName("media_id")
                        .HasColumnType("uuid");

                    b.Property<string>("MediaName")
                        .IsRequired()
                        .HasColumnName("media_name")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnName("reason")
                        .HasColumnType("text");

                    b.Property<string>("ScriptVersion")
                        .HasColumnName("script_version")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("status")
                        .HasColumnType("text")
                        .HasDefaultValue("HARD_FAIL");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("MediaId")
                        .HasName("IX_etl_media_id");

                    b.ToTable("etl","logs");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.ImagesForLabelling", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("BlobName")
                        .HasColumnName("blob_name")
                        .HasColumnType("text");

                    b.Property<string>("ContainerUrl")
                        .HasColumnName("container_url")
                        .HasColumnType("text");

                    b.Property<string>("Context")
                        .HasColumnName("context")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("createdon")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Filename")
                        .HasColumnName("filename")
                        .HasColumnType("text");

                    b.Property<Guid>("IdCreatorFk")
                        .HasColumnName("id_creator_fk")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageQuality")
                        .HasColumnName("image_quality")
                        .HasColumnType("text");

                    b.Property<string>("View")
                        .HasColumnName("view")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdCreatorFk")
                        .HasName("IX_images_for_labelling_IdCreatorFk");

                    b.ToTable("images_for_labelling","label");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<string>("BlobUrl")
                        .IsRequired()
                        .HasColumnName("blob_url")
                        .HasColumnType("text");

                    b.Property<string>("Createdby")
                        .IsRequired()
                        .HasColumnName("createdby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Createdon")
                        .HasColumnName("createdon")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnName("filename")
                        .HasColumnType("text");

                    b.Property<Guid?>("IdRefCampaignFk")
                        .HasColumnName("id_ref_campaign_fk")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdRefTrajectoryPointsFk")
                        .HasColumnName("id_ref_trajectory_points_fk")
                        .HasColumnType("uuid");

                    b.Property<BitArray>("Isdeleted")
                        .IsRequired()
                        .HasColumnName("isdeleted")
                        .HasColumnType("bit(1)");

                    b.Property<DateTime?>("Time")
                        .HasColumnName("time")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdRefCampaignFk");

                    b.HasIndex("IdRefTrajectoryPointsFk");

                    b.ToTable("media","campaign");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Test", b =>
                {
                    b.Property<int?>("B")
                        .HasColumnName("b")
                        .HasColumnType("integer");

                    b.ToTable("test");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Test2", b =>
                {
                    b.Property<string>("B")
                        .HasColumnName("b")
                        .HasColumnType("text");

                    b.ToTable("test2");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.TrajectoryPoint_Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("Createdon")
                        .HasColumnName("createdon")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double?>("Elevation")
                        .HasColumnName("elevation")
                        .HasColumnType("double precision");

                    b.Property<Guid>("IdRefCampaignFk")
                        .HasColumnName("id_ref_campaign_fk")
                        .HasColumnType("uuid");

                    b.Property<double?>("Lat")
                        .HasColumnName("lat")
                        .HasColumnType("double precision");

                    b.Property<double?>("Lon")
                        .HasColumnName("lon")
                        .HasColumnType("double precision");

                    b.Property<double?>("Speed")
                        .HasColumnName("speed")
                        .HasColumnType("double precision");

                    b.Property<Geometry>("TheGeom")
                        .HasColumnName("the_geom")
                        .HasColumnType("geometry");

                    b.Property<DateTime?>("Time")
                        .HasColumnName("time")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdRefCampaignFk");

                    b.HasIndex("TheGeom")
                        .HasName("trajectory_point_the_geom")
                        .HasAnnotation("Npgsql:IndexMethod", "gist");

                    b.ToTable("trajectory_point","campaign");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.TrashType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("trash_type","campaign");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Trash_Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("Createdon")
                        .HasColumnName("createdon")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double?>("Elevation")
                        .HasColumnName("elevation")
                        .HasColumnType("double precision");

                    b.Property<string>("Frame2Box")
                        .HasColumnName("frame_2_box")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("IdRefCampaignFk")
                        .HasColumnName("id_ref_campaign_fk")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdRefImageFk")
                        .HasColumnName("id_ref_image_fk")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdRefModelFk")
                        .HasColumnName("id_ref_model_fk")
                        .HasColumnType("uuid");

                    b.Property<int>("IdRefTrashTypeFk")
                        .HasColumnName("id_ref_trash_type_fk")
                        .HasColumnType("integer");

                    b.Property<double?>("Precision")
                        .HasColumnName("precision")
                        .HasColumnType("double precision");

                    b.Property<Geometry>("TheGeom")
                        .HasColumnName("the_geom")
                        .HasColumnType("geometry");

                    b.Property<DateTime?>("Time")
                        .HasColumnName("time")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdRefCampaignFk");

                    b.HasIndex("IdRefImageFk");

                    b.HasIndex("IdRefModelFk");

                    b.HasIndex("IdRefTrashTypeFk");

                    b.HasIndex("TheGeom")
                        .HasName("trash_the_geom")
                        .HasAnnotation("Npgsql:IndexMethod", "gist");

                    b.ToTable("trash","campaign");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("Createdon")
                        .HasColumnName("createdon")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasColumnType("text");

                    b.Property<bool>("Emailconfirmed")
                        .HasColumnName("emailconfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Experience")
                        .HasColumnName("experience")
                        .HasColumnType("text");

                    b.Property<string>("Firstname")
                        .HasColumnName("firstname")
                        .HasColumnType("text");

                    b.Property<bool>("Isdeleted")
                        .HasColumnName("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoggedOn")
                        .HasColumnName("lastloggedon")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Lastname")
                        .HasColumnName("lastname")
                        .HasColumnType("text");

                    b.Property<string>("Nickname")
                        .HasColumnName("nickname")
                        .HasColumnType("text");

                    b.Property<string>("Passwordhash")
                        .HasColumnName("passwordhash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Yearofbirth")
                        .HasColumnName("yearofbirth")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Firstname")
                        .HasName("user_firstname");

                    b.HasIndex("Lastname")
                        .HasName("user_lastname");

                    b.ToTable("user","campaign");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.BoundingBoxes", b =>
                {
                    b.HasOne("Data.SchemaMigrator.Models.ImagesForLabelling", "ImageForLabelling")
                        .WithMany("ImagesForLabellingBoundingBoxesNavigation")
                        .HasForeignKey("IdRefImagesForLabelling")
                        .HasConstraintName("id_ref_images_for_labelling_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Campaign_Campaign", b =>
                {
                    b.HasOne("Data.SchemaMigrator.Models.AiModel", "IdRefModelFkNavigation")
                        .WithMany("Campaigns_Campaign")
                        .HasForeignKey("IdRefModelFk")
                        .HasConstraintName("campaign_id_ref_model_fk_fkey");

                    b.HasOne("Data.SchemaMigrator.Models.User", "IdRefUserFkNavigation")
                        .WithMany("Campaigns_Campaign")
                        .HasForeignKey("IdRefUserFk")
                        .HasConstraintName("campaign_id_ref_user_fk_fkey");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Etl_Log", b =>
                {
                    b.HasOne("Data.SchemaMigrator.Models.Campaign_Campaign", "EtlLogs_Campaign_CampaignFKNavigation")
                        .WithMany("Etl_Logs")
                        .HasForeignKey("CampaignId")
                        .HasConstraintName("fk_campaign_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Media", b =>
                {
                    b.HasOne("Data.SchemaMigrator.Models.Campaign_Campaign", "IdRefCampaignFkNavigation")
                        .WithMany("Image")
                        .HasForeignKey("IdRefCampaignFk")
                        .HasConstraintName("image_id_ref_campaign_fk_fkey");

                    b.HasOne("Data.SchemaMigrator.Models.TrajectoryPoint_Campaign", "IdRefTrajectoryPointsFkNavigation")
                        .WithMany("Image")
                        .HasForeignKey("IdRefTrajectoryPointsFk")
                        .HasConstraintName("image_id_ref_trajectory_points_fk_fkey");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.TrajectoryPoint_Campaign", b =>
                {
                    b.HasOne("Data.SchemaMigrator.Models.Campaign_Campaign", "IdRefCampaignFkNavigation")
                        .WithMany("TrajectoryPoints_Campaign")
                        .HasForeignKey("IdRefCampaignFk")
                        .HasConstraintName("trajectory_point_id_ref_campaign_fk_fkey")
                        .IsRequired();
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Trash_Campaign", b =>
                {
                    b.HasOne("Data.SchemaMigrator.Models.Campaign_Campaign", "IdRefCampaignFkNavigation")
                        .WithMany("Trash1")
                        .HasForeignKey("IdRefCampaignFk")
                        .HasConstraintName("trash_id_ref_campaign_fk_fkey")
                        .IsRequired();

                    b.HasOne("Data.SchemaMigrator.Models.Media", "IdRefImageFkNavigation")
                        .WithMany("Trash1")
                        .HasForeignKey("IdRefImageFk")
                        .HasConstraintName("trash_id_ref_image_fk_fkey");

                    b.HasOne("Data.SchemaMigrator.Models.AiModel", "IdRefModelFkNavigation")
                        .WithMany("Trash1")
                        .HasForeignKey("IdRefModelFk")
                        .HasConstraintName("trash_id_ref_model_fk_fkey");
                });
#pragma warning restore 612, 618
        }
    }
}
