// <auto-generated />
using System;
using System.Collections;
using Data.SchemaMigrator.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.SchemaMigrator.Migrations
{
    [DbContext(typeof(PlasticoDbContext))]
    [Migration("20230424124729_userCguAndCampaignBi")]
    partial class userCguAndCampaignBi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_buffercache");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_stat_statements");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis_topology");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data.SchemaMigrator.Models.AiModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("Createdon")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<int?>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("model", "campaign");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Basin", b =>
                {
                    b.Property<string>("BasinId")
                        .HasColumnType("text")
                        .HasColumnName("basin_id");

                    b.Property<double>("AreaSquareKm")
                        .HasColumnType("double precision")
                        .HasColumnName("area_square_km");

                    b.Property<string>("BasinName")
                        .HasColumnType("text")
                        .HasColumnName("basin_name");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text")
                        .HasColumnName("country_code");

                    b.Property<string>("FeatureCollection")
                        .HasColumnType("jsonb")
                        .HasColumnName("feature_collection");

                    b.Property<int>("FecCount")
                        .HasColumnType("integer")
                        .HasColumnName("fec_count");

                    b.Property<Geometry>("TheGeom")
                        .HasColumnType("geometry")
                        .HasColumnName("the_geom");

                    b.Property<Geometry>("TheGeomBB")
                        .HasColumnType("geometry")
                        .HasColumnName("the_geom_bb");

                    b.HasKey("BasinId");

                    b.HasIndex("AreaSquareKm");

                    b.HasIndex("TheGeomBB");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TheGeomBB"), "gist");

                    b.ToTable("basin", "referential");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Bi_Log", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<double?>("ElapsedTime")
                        .HasColumnType("double precision")
                        .HasColumnName("elapsed_time");

                    b.Property<string>("FailedStep")
                        .HasColumnType("text")
                        .HasColumnName("failed_step");

                    b.Property<DateTime>("FinishedOn")
                        .HasColumnType("date")
                        .HasColumnName("finished_on");

                    b.Property<DateTime>("InitiatedOn")
                        .HasColumnType("date")
                        .HasColumnName("initiated_on");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("ScriptVersion")
                        .HasColumnType("text")
                        .HasColumnName("script_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("HARD_FAIL")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("IX_bi_campaign_id");

                    b.ToTable("bi", "logs");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.BoundingBoxes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<Guid>("IdCreatorFk")
                        .HasColumnType("uuid")
                        .HasColumnName("id_creator_fk");

                    b.Property<Guid>("IdRefImagesForLabelling")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ref_images_for_labelling");

                    b.Property<int>("IdRefTrashTypeFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_ref_trash_type_fk");

                    b.Property<int>("LocationX")
                        .HasColumnType("integer")
                        .HasColumnName("location_x");

                    b.Property<int>("LocationY")
                        .HasColumnType("integer")
                        .HasColumnName("location_y");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("IdCreatorFk")
                        .HasDatabaseName("IX_bounding_boxes_IdCreatorFk");

                    b.HasIndex("IdRefImagesForLabelling");

                    b.HasIndex("IdRefTrashTypeFk")
                        .HasDatabaseName("IX_bounding_boxes_IdRefTrashTypeFk");

                    b.ToTable("bounding_boxes", "label");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.CampaignRiver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdon")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<bool?>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("disabled");

                    b.Property<decimal?>("Distance")
                        .HasColumnType("numeric")
                        .HasColumnName("distance");

                    b.Property<string>("FeatureCollection")
                        .HasColumnType("jsonb")
                        .HasColumnName("feature_collection");

                    b.Property<Guid?>("IdRefCampaignFk")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ref_campaign_fk");

                    b.Property<int>("IdRefRiverFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_ref_river_fk");

                    b.Property<Geometry>("TheGeom")
                        .HasColumnType("geometry")
                        .HasColumnName("the_geom");

                    b.Property<int?>("TrashCount")
                        .HasColumnType("integer")
                        .HasColumnName("trash_count");

                    b.Property<decimal?>("TrashPerKm")
                        .HasColumnType("numeric")
                        .HasColumnName("trash_per_km");

                    b.HasKey("Id");

                    b.HasIndex("IdRefCampaignFk");

                    b.HasIndex("TheGeom")
                        .HasDatabaseName("campaign_river_the_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TheGeom"), "gist");

                    b.ToTable("campaign_river", "bi");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.CampaignRiver_Bi_Temp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdon")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<decimal?>("Distance")
                        .HasColumnType("numeric")
                        .HasColumnName("distance");

                    b.Property<Guid?>("IdRefCampaignFk")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ref_campaign_fk");

                    b.Property<int>("IdRefRiverFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_ref_river_fk");

                    b.Property<Geometry>("TheGeom")
                        .HasColumnType("geometry")
                        .HasColumnName("the_geom");

                    b.Property<int?>("TrashCount")
                        .HasColumnType("integer")
                        .HasColumnName("trash_count");

                    b.Property<decimal?>("TrashPerKm")
                        .HasColumnType("numeric")
                        .HasColumnName("trash_per_km");

                    b.HasKey("Id");

                    b.HasIndex("IdRefCampaignFk")
                        .HasDatabaseName("IX_campaign_river_id_ref_campaign_fk1");

                    b.ToTable("campaign_river", "bi_temp");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Campaign_Bi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AvgSpeed")
                        .HasColumnType("integer")
                        .HasColumnName("avg_speed");

                    b.Property<DateTime?>("Createdon")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<double?>("Distance")
                        .HasColumnType("double precision")
                        .HasColumnName("distance");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<Geometry>("EndPoint")
                        .HasColumnType("geometry")
                        .HasColumnName("end_point");

                    b.Property<Guid?>("IdRefModelFk")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ref_model_fk");

                    b.Property<Guid?>("IdRefUserFk")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ref_user_fk");

                    b.Property<bool?>("Isaidriven")
                        .HasColumnType("boolean")
                        .HasColumnName("isaidriven");

                    b.Property<string>("Locomotion")
                        .HasColumnType("text")
                        .HasColumnName("locomotion");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark");

                    b.Property<string>("Riverside")
                        .HasColumnType("text")
                        .HasColumnName("riverside");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<Geometry>("StartPoint")
                        .HasColumnType("geometry")
                        .HasColumnName("start_point");

                    b.Property<Geometry>("TheGeom")
                        .HasColumnType("geometry")
                        .HasColumnName("the_geom");

                    b.Property<int?>("TrashCount")
                        .HasColumnType("integer")
                        .HasColumnName("trash_count");

                    b.Property<decimal?>("TrashPerKm")
                        .HasColumnType("numeric")
                        .HasColumnName("trash_per_km");

                    b.HasKey("Id");

                    b.HasIndex("EndPoint")
                        .HasDatabaseName("campaign_end_point");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("EndPoint"), "gist");

                    b.HasIndex("Id")
                        .HasDatabaseName("campaign_id");

                    b.HasIndex("StartPoint")
                        .HasDatabaseName("campaign_start_point");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("StartPoint"), "gist");

                    b.ToTable("campaign", "bi");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Campaign_Bi_Temp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AvgSpeed")
                        .HasColumnType("integer")
                        .HasColumnName("avg_speed");

                    b.Property<DateTime?>("Createdon")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<double?>("Distance")
                        .HasColumnType("double precision")
                        .HasColumnName("distance");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<Geometry>("EndPoint")
                        .HasColumnType("geometry")
                        .HasColumnName("end_point");

                    b.Property<double?>("EndPointDistanceSea")
                        .HasColumnType("double precision")
                        .HasColumnName("end_point_distance_sea");

                    b.Property<Guid?>("IdRefModelFk")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ref_model_fk");

                    b.Property<Guid?>("IdRefUserFk")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ref_user_fk");

                    b.Property<bool?>("Isaidriven")
                        .HasColumnType("boolean")
                        .HasColumnName("isaidriven");

                    b.Property<string>("Locomotion")
                        .HasColumnType("text")
                        .HasColumnName("locomotion");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark");

                    b.Property<string>("Riverside")
                        .HasColumnType("text")
                        .HasColumnName("riverside");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<Geometry>("StartPoint")
                        .HasColumnType("geometry")
                        .HasColumnName("start_point");

                    b.Property<double?>("StartPointDistanceSea")
                        .HasColumnType("double precision")
                        .HasColumnName("start_point_distance_sea");

                    b.Property<Geometry>("TheGeom")
                        .HasColumnType("geometry")
                        .HasColumnName("the_geom");

                    b.Property<int?>("TrashCount")
                        .HasColumnType("integer")
                        .HasColumnName("trash_count");

                    b.Property<decimal?>("TrashPerKm")
                        .HasColumnType("numeric")
                        .HasColumnName("trash_per_km");

                    b.HasKey("Id");

                    b.ToTable("campaign", "bi_temp");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Campaign_Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("Createdon")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<bool?>("HasBeenComputed")
                        .HasColumnType("boolean")
                        .HasColumnName("has_been_computed");

                    b.Property<Guid?>("IdRefModelFk")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ref_model_fk");

                    b.Property<Guid?>("IdRefUserFk")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ref_user_fk");

                    b.Property<bool?>("Isaidriven")
                        .HasColumnType("boolean")
                        .HasColumnName("isaidriven");

                    b.Property<string>("Locomotion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("locomotion");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark");

                    b.Property<string>("Riverside")
                        .HasColumnType("text")
                        .HasColumnName("riverside");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("campaign_id");

                    b.HasIndex("IdRefModelFk");

                    b.HasIndex("IdRefUserFk");

                    b.ToTable("campaign", "campaign");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime?>("Createdon")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<string>("FeatureCollection")
                        .HasColumnType("jsonb")
                        .HasColumnName("feature_collection");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Geometry>("TheGeom")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("the_geom");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .HasDatabaseName("country_code");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("country_name_key");

                    b.HasIndex("TheGeom")
                        .HasDatabaseName("country_the_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TheGeom"), "gist");

                    b.ToTable("country", "referential");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime?>("Createdon")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<int?>("IdRefStateFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_ref_state_fk");

                    b.Property<string>("IdSource")
                        .HasColumnType("text")
                        .HasColumnName("id_source");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Geometry>("TheGeom")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("the_geom");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .HasDatabaseName("referential_department_code");

                    b.HasIndex("IdRefStateFk");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("department_name_key");

                    b.HasIndex("TheGeom")
                        .HasDatabaseName("referential_department_the_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TheGeom"), "gist");

                    b.ToTable("department", "referential");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Etl_Log", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<string>("Container")
                        .HasColumnType("text")
                        .HasColumnName("container");

                    b.Property<double?>("ElapsedTime")
                        .HasColumnType("double precision")
                        .HasColumnName("elapsed_time");

                    b.Property<DateTime>("FinishedOn")
                        .HasColumnType("date")
                        .HasColumnName("finished_on");

                    b.Property<DateTime>("InitiatedOn")
                        .HasColumnType("date")
                        .HasColumnName("initiated_on");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_id");

                    b.Property<string>("MediaName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("media_name");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("ScriptVersion")
                        .HasColumnType("text")
                        .HasColumnName("script_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("HARD_FAIL")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("MediaId")
                        .HasDatabaseName("IX_etl_media_id");

                    b.ToTable("etl", "logs");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.ImagesForLabelling", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("BlobName")
                        .HasColumnType("text")
                        .HasColumnName("blob_name");

                    b.Property<string>("ContainerUrl")
                        .HasColumnType("text")
                        .HasColumnName("container_url");

                    b.Property<string>("Context")
                        .HasColumnType("text")
                        .HasColumnName("context");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<string>("Filename")
                        .HasColumnType("text")
                        .HasColumnName("filename");

                    b.Property<Guid>("IdCreatorFk")
                        .HasColumnType("uuid")
                        .HasColumnName("id_creator_fk");

                    b.Property<string>("ImageQuality")
                        .HasColumnType("text")
                        .HasColumnName("image_quality");

                    b.Property<string>("View")
                        .HasColumnType("text")
                        .HasColumnName("view");

                    b.HasKey("Id");

                    b.HasIndex("IdCreatorFk")
                        .HasDatabaseName("IX_images_for_labelling_IdCreatorFk");

                    b.ToTable("images_for_labelling", "label");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.LimitsLandSea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("CodeHydro")
                        .HasColumnType("text")
                        .HasColumnName("code_hydro");

                    b.Property<DateTime?>("Createdon")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<int?>("IdRefCountryFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_ref_country_fk");

                    b.Property<string>("IdSource")
                        .HasColumnType("text")
                        .HasColumnName("id_source");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Nature")
                        .HasColumnType("text")
                        .HasColumnName("nature");

                    b.Property<string>("Origine")
                        .HasColumnType("text")
                        .HasColumnName("origine");

                    b.Property<Geometry>("TheGeom")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("the_geom");

                    b.HasKey("Id");

                    b.HasIndex("IdRefCountryFk");

                    b.HasIndex("TheGeom")
                        .HasDatabaseName("limits_land_sea_the_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TheGeom"), "gist");

                    b.ToTable("limits_land_sea", "referential");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlobUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("blob_url");

                    b.Property<string>("Createdby")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("Createdon")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("filename");

                    b.Property<Guid?>("IdRefCampaignFk")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ref_campaign_fk");

                    b.Property<Guid?>("IdRefTrajectoryPointsFk")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ref_trajectory_points_fk");

                    b.Property<BitArray>("Isdeleted")
                        .IsRequired()
                        .HasColumnType("bit(1)")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.HasIndex("IdRefCampaignFk");

                    b.HasIndex("IdRefTrajectoryPointsFk");

                    b.ToTable("media", "campaign");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Municipality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime?>("Createdon")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<int?>("IdRefDepartmentFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_ref_department_fk");

                    b.Property<string>("IdSource")
                        .HasColumnType("text")
                        .HasColumnName("id_source");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Geometry>("TheGeom")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("the_geom");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .HasDatabaseName("municipality_code");

                    b.HasIndex("IdRefDepartmentFk");

                    b.HasIndex("TheGeom")
                        .HasDatabaseName("municipality_the_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TheGeom"), "gist");

                    b.ToTable("municipality", "referential");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Pipelines", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool?>("CampaignHasBeenComputed")
                        .HasColumnType("boolean")
                        .HasColumnName("campaign_has_been_computed");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<bool?>("RiverHasBeenComputed")
                        .HasColumnType("boolean")
                        .HasColumnName("river_has_been_computed");

                    b.HasKey("Id");

                    b.ToTable("pipelines", "bi_temp");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.River_Bi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("CountTrash")
                        .HasColumnType("double precision")
                        .HasColumnName("count_trash");

                    b.Property<DateTime?>("Createdon")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<double?>("DistanceMonitored")
                        .HasColumnType("double precision")
                        .HasColumnName("distance_monitored");

                    b.Property<string>("FeatureCollection")
                        .HasColumnType("jsonb")
                        .HasColumnName("feature_collection");

                    b.Property<int?>("Importance")
                        .HasColumnType("integer")
                        .HasColumnName("importance");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("NbCampaign")
                        .HasColumnType("integer")
                        .HasColumnName("nb_campaign");

                    b.Property<Geometry>("TheGeom")
                        .HasColumnType("geometry")
                        .HasColumnName("the_geom");

                    b.Property<Geometry>("TheGeomMonitored")
                        .HasColumnType("geometry")
                        .HasColumnName("the_geom_monitored");

                    b.Property<decimal?>("TrashPerKm")
                        .HasColumnType("numeric")
                        .HasColumnName("trash_per_km");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("river_id");

                    b.HasIndex("Importance")
                        .HasDatabaseName("river_bi_importance");

                    b.HasIndex("TheGeom")
                        .HasDatabaseName("river_the_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TheGeom"), "gist");

                    b.ToTable("river", "bi");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.River_Bi_Temp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("CountTrash")
                        .HasColumnType("double precision")
                        .HasColumnName("count_trash");

                    b.Property<DateTime?>("Createdon")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<double?>("DistanceMonitored")
                        .HasColumnType("double precision")
                        .HasColumnName("distance_monitored");

                    b.Property<int?>("Importance")
                        .HasColumnType("integer")
                        .HasColumnName("importance");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("NbCampaign")
                        .HasColumnType("integer")
                        .HasColumnName("nb_campaign");

                    b.Property<Geometry>("TheGeom")
                        .HasColumnType("geometry")
                        .HasColumnName("the_geom");

                    b.Property<Geometry>("TheGeomMonitored")
                        .HasColumnType("geometry")
                        .HasColumnName("the_geom_monitored");

                    b.Property<decimal?>("TrashPerKm")
                        .HasColumnType("numeric")
                        .HasColumnName("trash_per_km");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("bi_temp_river_id");

                    b.ToTable("river", "bi_temp");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.River_Referential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime?>("Createdon")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<int?>("Importance")
                        .HasColumnType("integer")
                        .HasColumnName("importance");

                    b.Property<string>("Length")
                        .HasColumnType("text")
                        .HasColumnName("length");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Geometry>("TheGeom")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("the_geom");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("river_id");

                    b.HasIndex("Importance")
                        .HasDatabaseName("river_importance");

                    b.HasIndex("TheGeom")
                        .HasDatabaseName("river_the_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TheGeom"), "gist");

                    b.ToTable("river", "referential");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Segment_Bi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("CountTrash")
                        .HasColumnType("double precision")
                        .HasColumnName("count_trash");

                    b.Property<double?>("CountTrashRiver")
                        .HasColumnType("double precision")
                        .HasColumnName("count_trash_river");

                    b.Property<DateTime?>("Createdon")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<double?>("DistanceMonitored")
                        .HasColumnType("double precision")
                        .HasColumnName("distance_monitored");

                    b.Property<double?>("DistanceMonitoredRiver")
                        .HasColumnType("double precision")
                        .HasColumnName("distance_monitored_river");

                    b.Property<string>("FeatureCollection")
                        .HasColumnType("jsonb")
                        .HasColumnName("feature_collection");

                    b.Property<int?>("Importance")
                        .HasColumnType("integer")
                        .HasColumnName("importance");

                    b.Property<int?>("NbCampaign")
                        .HasColumnType("integer")
                        .HasColumnName("nb_campaign");

                    b.Property<int?>("NbCampaignRiver")
                        .HasColumnType("integer")
                        .HasColumnName("nb_campaign_river");

                    b.Property<Geometry>("TheGeom")
                        .HasColumnType("geometry")
                        .HasColumnName("the_geom");

                    b.Property<Geometry>("TheGeomMonitored")
                        .HasColumnType("geometry")
                        .HasColumnName("the_geom_monitored");

                    b.Property<decimal?>("TrashPerKm")
                        .HasColumnType("numeric")
                        .HasColumnName("trash_per_km");

                    b.Property<decimal?>("TrashPerKmRiver")
                        .HasColumnType("numeric")
                        .HasColumnName("trash_per_km_river");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("bi_segment_id");

                    b.HasIndex("Importance")
                        .HasDatabaseName("bi_segment_importance");

                    b.HasIndex("TheGeom")
                        .HasDatabaseName("segment_the_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TheGeom"), "gist");

                    b.ToTable("segment", "bi");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Segment_Bi_Temp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("CountTrash")
                        .HasColumnType("double precision")
                        .HasColumnName("count_trash");

                    b.Property<double?>("CountTrashRiver")
                        .HasColumnType("double precision")
                        .HasColumnName("count_trash_river");

                    b.Property<DateTime?>("Createdon")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<double?>("DistanceMonitored")
                        .HasColumnType("double precision")
                        .HasColumnName("distance_monitored");

                    b.Property<double?>("DistanceMonitoredRiver")
                        .HasColumnType("double precision")
                        .HasColumnName("distance_monitored_river");

                    b.Property<int?>("Importance")
                        .HasColumnType("integer")
                        .HasColumnName("importance");

                    b.Property<int?>("NbCampaign")
                        .HasColumnType("integer")
                        .HasColumnName("nb_campaign");

                    b.Property<int?>("NbCampaignRiver")
                        .HasColumnType("integer")
                        .HasColumnName("nb_campaign_river");

                    b.Property<Geometry>("TheGeom")
                        .HasColumnType("geometry")
                        .HasColumnName("the_geom");

                    b.Property<Geometry>("TheGeomMonitored")
                        .HasColumnType("geometry")
                        .HasColumnName("the_geom_monitored");

                    b.Property<decimal?>("TrashPerKm")
                        .HasColumnType("numeric")
                        .HasColumnName("trash_per_km");

                    b.Property<decimal?>("TrashPerKmRiver")
                        .HasColumnType("numeric")
                        .HasColumnName("trash_per_km_river");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("bi_temp_segment_id");

                    b.ToTable("segment", "bi_temp");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Segment_Referential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bras")
                        .HasColumnType("text")
                        .HasColumnName("bras");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("CodeHydro")
                        .HasColumnType("text")
                        .HasColumnName("code_hydro");

                    b.Property<DateTime?>("Createdon")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<int?>("IdRefCountryFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_ref_country_fk");

                    b.Property<int>("IdRefRiverFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_ref_river_fk");

                    b.Property<int?>("Importance")
                        .HasColumnType("integer")
                        .HasColumnName("importance");

                    b.Property<decimal?>("Length")
                        .HasColumnType("numeric")
                        .HasColumnName("length");

                    b.Property<string>("Nature")
                        .HasColumnType("text")
                        .HasColumnName("nature");

                    b.Property<string>("Origine")
                        .HasColumnType("text")
                        .HasColumnName("origine");

                    b.Property<int?>("StrahlerRank")
                        .HasColumnType("integer")
                        .HasColumnName("strahler_rank");

                    b.Property<Geometry>("TheGeom")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("the_geom");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("segment_id");

                    b.HasIndex("IdRefCountryFk");

                    b.HasIndex("IdRefRiverFk");

                    b.HasIndex("Importance")
                        .HasDatabaseName("segment_importance");

                    b.HasIndex("TheGeom")
                        .HasDatabaseName("segment_the_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TheGeom"), "gist");

                    b.ToTable("segment", "referential");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime?>("Createdon")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<int?>("IdRefCountryFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_ref_country_fk");

                    b.Property<string>("IdSource")
                        .HasColumnType("text")
                        .HasColumnName("id_source");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Geometry>("TheGeom")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("the_geom");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .HasDatabaseName("state_code");

                    b.HasIndex("IdRefCountryFk");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("state_name_key");

                    b.HasIndex("TheGeom")
                        .HasDatabaseName("state_the_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TheGeom"), "gist");

                    b.ToTable("state", "referential");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Test", b =>
                {
                    b.Property<int?>("B")
                        .HasColumnType("integer")
                        .HasColumnName("b");

                    b.ToTable("test", (string)null);
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Test2", b =>
                {
                    b.Property<string>("B")
                        .HasColumnType("text")
                        .HasColumnName("b");

                    b.ToTable("test2", (string)null);
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.TrajectoryPointRiver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdon")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<Guid>("IdRefCampaignFk")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ref_campaign_fk");

                    b.Property<int>("IdRefRiverFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_ref_river_fk");

                    b.Property<int>("IdRefSegmentFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_ref_segment_fk");

                    b.Property<Guid>("IdRefTrajectoryPointFk")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ref_trajectory_point_fk");

                    b.Property<Geometry>("TheGeom")
                        .HasColumnType("geometry")
                        .HasColumnName("the_geom");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.HasIndex("IdRefCampaignFk");

                    b.ToTable("trajectory_point_river", "bi");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.TrajectoryPointRiver_Bi_Temp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdon")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<Guid>("IdRefCampaignFk")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ref_campaign_fk");

                    b.Property<int>("IdRefRiverFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_ref_river_fk");

                    b.Property<int>("IdRefSegmentFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_ref_segment_fk");

                    b.Property<Guid>("IdRefTrajectoryPointFk")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ref_trajectory_point_fk");

                    b.Property<Geometry>("TheGeom")
                        .HasColumnType("geometry")
                        .HasColumnName("the_geom");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.HasIndex("IdRefCampaignFk")
                        .HasDatabaseName("IX_trajectory_point_river_id_ref_campaign_fk1");

                    b.HasIndex("IdRefRiverFk");

                    b.ToTable("trajectory_point_river", "bi_temp");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.TrajectoryPoint_Bi", b =>
                {
                    b.Property<DateTime?>("Createdon")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<double?>("Distance")
                        .HasColumnType("double precision")
                        .HasColumnName("distance");

                    b.Property<double?>("Elevation")
                        .HasColumnType("double precision")
                        .HasColumnName("elevation");

                    b.Property<Guid?>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("IdRefCampaignFk")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ref_campaign_fk");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double?>("Lon")
                        .HasColumnType("double precision")
                        .HasColumnName("lon");

                    b.Property<double?>("Speed")
                        .HasColumnType("double precision")
                        .HasColumnName("speed");

                    b.Property<Geometry>("TheGeom")
                        .HasColumnType("geometry")
                        .HasColumnName("the_geom");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<TimeSpan?>("TimeDiff")
                        .HasColumnType("interval")
                        .HasColumnName("time_diff");

                    b.HasIndex("IdRefCampaignFk");

                    b.ToTable("trajectory_point", "bi");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.TrajectoryPoint_Bi_Temp", b =>
                {
                    b.Property<DateTime?>("Createdon")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<double?>("Distance")
                        .HasColumnType("double precision")
                        .HasColumnName("distance");

                    b.Property<double?>("Elevation")
                        .HasColumnType("double precision")
                        .HasColumnName("elevation");

                    b.Property<Guid?>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("IdRefCampaignFk")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ref_campaign_fk");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double?>("Lon")
                        .HasColumnType("double precision")
                        .HasColumnName("lon");

                    b.Property<double?>("Speed")
                        .HasColumnType("double precision")
                        .HasColumnName("speed");

                    b.Property<Geometry>("TheGeom")
                        .HasColumnType("geometry")
                        .HasColumnName("the_geom");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<TimeSpan?>("TimeDiff")
                        .HasColumnType("interval")
                        .HasColumnName("time_diff");

                    b.HasIndex("Id");

                    b.HasIndex("IdRefCampaignFk");

                    b.ToTable("trajectory_point", "bi_temp");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.TrajectoryPoint_Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("Createdon")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<double?>("Elevation")
                        .HasColumnType("double precision")
                        .HasColumnName("elevation");

                    b.Property<Guid>("IdRefCampaignFk")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ref_campaign_fk");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double?>("Lon")
                        .HasColumnType("double precision")
                        .HasColumnName("lon");

                    b.Property<double?>("Speed")
                        .HasColumnType("double precision")
                        .HasColumnName("speed");

                    b.Property<Geometry>("TheGeom")
                        .HasColumnType("geometry")
                        .HasColumnName("the_geom");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.HasIndex("IdRefCampaignFk");

                    b.HasIndex("TheGeom")
                        .HasDatabaseName("trajectory_point_the_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TheGeom"), "gist");

                    b.ToTable("trajectory_point", "campaign");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.TrashRiver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdon")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<string>("FeatureCollection")
                        .HasColumnType("jsonb")
                        .HasColumnName("feature_collection");

                    b.Property<Guid>("IdRefCampaignFk")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ref_campaign_fk");

                    b.Property<int>("IdRefRiverFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_ref_river_fk");

                    b.Property<int>("IdRefSegmentFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_ref_segment_fk");

                    b.Property<Guid>("IdRefTrashFk")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ref_trash_fk");

                    b.Property<Geometry>("TheGeom")
                        .HasColumnType("geometry")
                        .HasColumnName("the_geom");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("IdRefCampaignFk");

                    b.HasIndex("IdRefTrashFk");

                    b.HasIndex("TheGeom")
                        .HasDatabaseName("trash_river_the_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TheGeom"), "gist");

                    b.ToTable("trash_river", "bi");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.TrashRiver_Bi_Temp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdon")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<Guid>("IdRefCampaignFk")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ref_campaign_fk");

                    b.Property<int>("IdRefRiverFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_ref_river_fk");

                    b.Property<int>("IdRefSegmentFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_ref_segment_fk");

                    b.Property<Guid>("IdRefTrashFk")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ref_trash_fk");

                    b.Property<Geometry>("TheGeom")
                        .HasColumnType("geometry")
                        .HasColumnName("the_geom");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("IX_trash_river_id1");

                    b.HasIndex("IdRefCampaignFk")
                        .HasDatabaseName("IX_trash_river_id_ref_campaign_fk1");

                    b.HasIndex("IdRefRiverFk");

                    b.HasIndex("IdRefSegmentFk");

                    b.ToTable("trash_river", "bi_temp");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.TrashType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("trash_type", "campaign");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Trash_Bi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text")
                        .HasColumnName("country_code");

                    b.Property<string>("CountryName")
                        .HasColumnType("text")
                        .HasColumnName("country_name");

                    b.Property<DateTime?>("Createdon")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("text")
                        .HasColumnName("department_code");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("text")
                        .HasColumnName("department_name");

                    b.Property<double?>("Elevation")
                        .HasColumnType("double precision")
                        .HasColumnName("elevation");

                    b.Property<Guid>("IdRefCampaignFk")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ref_campaign_fk");

                    b.Property<Guid?>("IdRefImageFk")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ref_image_fk");

                    b.Property<Guid?>("IdRefModelFk")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ref_model_fk");

                    b.Property<int>("IdRefTrashTypeFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_ref_trash_type_fk");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double?>("Lon")
                        .HasColumnType("double precision")
                        .HasColumnName("lon");

                    b.Property<string>("MunicipalityCode")
                        .HasColumnType("text")
                        .HasColumnName("municipality_code");

                    b.Property<string>("MunicipalityName")
                        .HasColumnType("text")
                        .HasColumnName("municipality_name");

                    b.Property<double?>("Precision")
                        .HasColumnType("double precision")
                        .HasColumnName("precision");

                    b.Property<string>("StateCode")
                        .HasColumnType("text")
                        .HasColumnName("state_code");

                    b.Property<string>("StateName")
                        .HasColumnType("text")
                        .HasColumnName("state_name");

                    b.Property<Geometry>("TheGeom")
                        .HasColumnType("geometry")
                        .HasColumnName("the_geom");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("IdRefCampaignFk");

                    b.HasIndex("TheGeom")
                        .HasDatabaseName("bi_trash_the_geom");

                    b.ToTable("trash", "bi");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Trash_Bi_Temp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text")
                        .HasColumnName("country_code");

                    b.Property<string>("CountryName")
                        .HasColumnType("text")
                        .HasColumnName("country_name");

                    b.Property<DateTime?>("Createdon")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("text")
                        .HasColumnName("department_code");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("text")
                        .HasColumnName("department_name");

                    b.Property<double?>("Elevation")
                        .HasColumnType("double precision")
                        .HasColumnName("elevation");

                    b.Property<Guid>("IdRefCampaignFk")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ref_campaign_fk");

                    b.Property<Guid?>("IdRefImageFk")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ref_media_fk");

                    b.Property<Guid?>("IdRefModelFk")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ref_model_fk");

                    b.Property<int>("IdRefTrashTypeFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_ref_trash_type_fk");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double?>("Lon")
                        .HasColumnType("double precision")
                        .HasColumnName("lon");

                    b.Property<string>("MunicipalityCode")
                        .HasColumnType("text")
                        .HasColumnName("municipality_code");

                    b.Property<string>("MunicipalityName")
                        .HasColumnType("text")
                        .HasColumnName("municipality_name");

                    b.Property<double?>("Precision")
                        .HasColumnType("double precision")
                        .HasColumnName("precision");

                    b.Property<string>("StateCode")
                        .HasColumnType("text")
                        .HasColumnName("state_code");

                    b.Property<string>("StateName")
                        .HasColumnType("text")
                        .HasColumnName("state_name");

                    b.Property<Geometry>("TheGeom")
                        .HasColumnType("geometry")
                        .HasColumnName("the_geom");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("IX_trash_id1");

                    b.HasIndex("IdRefCampaignFk")
                        .HasDatabaseName("IX_trash_id_ref_campaign_fk1");

                    b.HasIndex("TheGeom")
                        .HasDatabaseName("bi_trash_the_geom");

                    b.ToTable("trash", "bi_temp");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Trash_Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("Createdon")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<double?>("Elevation")
                        .HasColumnType("double precision")
                        .HasColumnName("elevation");

                    b.Property<string>("Frame2Box")
                        .HasColumnType("jsonb")
                        .HasColumnName("frame_2_box");

                    b.Property<Guid>("IdRefCampaignFk")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ref_campaign_fk");

                    b.Property<Guid?>("IdRefImageFk")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ref_image_fk");

                    b.Property<Guid?>("IdRefModelFk")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ref_model_fk");

                    b.Property<int>("IdRefTrashTypeFk")
                        .HasColumnType("integer")
                        .HasColumnName("id_ref_trash_type_fk");

                    b.Property<double?>("Precision")
                        .HasColumnType("double precision")
                        .HasColumnName("precision");

                    b.Property<Geometry>("TheGeom")
                        .HasColumnType("geometry")
                        .HasColumnName("the_geom");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.HasIndex("IdRefCampaignFk")
                        .HasDatabaseName("IX_trash_id_ref_campaign_fk2");

                    b.HasIndex("IdRefImageFk");

                    b.HasIndex("IdRefModelFk");

                    b.HasIndex("IdRefTrashTypeFk");

                    b.HasIndex("TheGeom")
                        .HasDatabaseName("trash_the_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TheGeom"), "gist");

                    b.ToTable("trash", "campaign");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("CGUValidatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cguvalidateddate");

                    b.Property<DateTime?>("Createdon")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("Emailconfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("emailconfirmed");

                    b.Property<string>("Experience")
                        .HasColumnType("text")
                        .HasColumnName("experience");

                    b.Property<string>("Firstname")
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<bool>("Isdeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("LastLoggedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastloggedon");

                    b.Property<string>("Lastname")
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<string>("Nickname")
                        .HasColumnType("text")
                        .HasColumnName("nickname");

                    b.Property<string>("Passwordhash")
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.Property<DateTime?>("Yearofbirth")
                        .HasColumnType("date")
                        .HasColumnName("yearofbirth");

                    b.HasKey("Id");

                    b.HasIndex("Firstname")
                        .HasDatabaseName("user_firstname");

                    b.HasIndex("Lastname")
                        .HasDatabaseName("user_lastname");

                    b.ToTable("user", "campaign");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.BoundingBoxes", b =>
                {
                    b.HasOne("Data.SchemaMigrator.Models.ImagesForLabelling", "ImageForLabelling")
                        .WithMany("ImagesForLabellingBoundingBoxesNavigation")
                        .HasForeignKey("IdRefImagesForLabelling")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("id_ref_images_for_labelling_fk");

                    b.Navigation("ImageForLabelling");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Campaign_Campaign", b =>
                {
                    b.HasOne("Data.SchemaMigrator.Models.AiModel", "IdRefModelFkNavigation")
                        .WithMany("Campaigns_Campaign")
                        .HasForeignKey("IdRefModelFk")
                        .HasConstraintName("campaign_id_ref_model_fk_fkey");

                    b.HasOne("Data.SchemaMigrator.Models.User", "IdRefUserFkNavigation")
                        .WithMany("Campaigns_Campaign")
                        .HasForeignKey("IdRefUserFk")
                        .HasConstraintName("campaign_id_ref_user_fk_fkey");

                    b.Navigation("IdRefModelFkNavigation");

                    b.Navigation("IdRefUserFkNavigation");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Department", b =>
                {
                    b.HasOne("Data.SchemaMigrator.Models.State", "IdRefStateFkNavigation")
                        .WithMany("Department")
                        .HasForeignKey("IdRefStateFk")
                        .HasConstraintName("department_id_ref_state_fk_fkey");

                    b.Navigation("IdRefStateFkNavigation");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Etl_Log", b =>
                {
                    b.HasOne("Data.SchemaMigrator.Models.Campaign_Campaign", "EtlLogs_Campaign_CampaignFKNavigation")
                        .WithMany("Etl_Logs")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_id");

                    b.Navigation("EtlLogs_Campaign_CampaignFKNavigation");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.LimitsLandSea", b =>
                {
                    b.HasOne("Data.SchemaMigrator.Models.Country", "IdRefCountryFkNavigation")
                        .WithMany("LimitsLandSea")
                        .HasForeignKey("IdRefCountryFk")
                        .HasConstraintName("limits_land_sea_id_ref_country_fk_fkey");

                    b.Navigation("IdRefCountryFkNavigation");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Media", b =>
                {
                    b.HasOne("Data.SchemaMigrator.Models.Campaign_Campaign", "IdRefCampaignFkNavigation")
                        .WithMany("Image")
                        .HasForeignKey("IdRefCampaignFk")
                        .HasConstraintName("image_id_ref_campaign_fk_fkey");

                    b.HasOne("Data.SchemaMigrator.Models.TrajectoryPoint_Campaign", "IdRefTrajectoryPointsFkNavigation")
                        .WithMany("Image")
                        .HasForeignKey("IdRefTrajectoryPointsFk")
                        .HasConstraintName("image_id_ref_trajectory_points_fk_fkey");

                    b.Navigation("IdRefCampaignFkNavigation");

                    b.Navigation("IdRefTrajectoryPointsFkNavigation");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Municipality", b =>
                {
                    b.HasOne("Data.SchemaMigrator.Models.Department", "IdRefDepartmentFkNavigation")
                        .WithMany("Municipality")
                        .HasForeignKey("IdRefDepartmentFk")
                        .HasConstraintName("municipality_id_ref_department_fk_fkey");

                    b.Navigation("IdRefDepartmentFkNavigation");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Segment_Referential", b =>
                {
                    b.HasOne("Data.SchemaMigrator.Models.Country", "IdRefCountryFkNavigation")
                        .WithMany("Segment")
                        .HasForeignKey("IdRefCountryFk")
                        .HasConstraintName("segment_id_ref_country_fk_fkey");

                    b.HasOne("Data.SchemaMigrator.Models.River_Referential", "IdRefRiverFkNavigation")
                        .WithMany("Segment")
                        .HasForeignKey("IdRefRiverFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("segment_id_ref_river_fk_fkey");

                    b.Navigation("IdRefCountryFkNavigation");

                    b.Navigation("IdRefRiverFkNavigation");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.State", b =>
                {
                    b.HasOne("Data.SchemaMigrator.Models.Country", "IdRefCountryFkNavigation")
                        .WithMany("State")
                        .HasForeignKey("IdRefCountryFk")
                        .HasConstraintName("state_id_ref_country_fk_fkey");

                    b.Navigation("IdRefCountryFkNavigation");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.TrajectoryPoint_Campaign", b =>
                {
                    b.HasOne("Data.SchemaMigrator.Models.Campaign_Campaign", "IdRefCampaignFkNavigation")
                        .WithMany("TrajectoryPoints_Campaign")
                        .HasForeignKey("IdRefCampaignFk")
                        .IsRequired()
                        .HasConstraintName("trajectory_point_id_ref_campaign_fk_fkey");

                    b.Navigation("IdRefCampaignFkNavigation");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Trash_Campaign", b =>
                {
                    b.HasOne("Data.SchemaMigrator.Models.Campaign_Campaign", "IdRefCampaignFkNavigation")
                        .WithMany("Trash1")
                        .HasForeignKey("IdRefCampaignFk")
                        .IsRequired()
                        .HasConstraintName("trash_id_ref_campaign_fk_fkey");

                    b.HasOne("Data.SchemaMigrator.Models.Media", "IdRefImageFkNavigation")
                        .WithMany("Trash1")
                        .HasForeignKey("IdRefImageFk")
                        .HasConstraintName("trash_id_ref_image_fk_fkey");

                    b.HasOne("Data.SchemaMigrator.Models.AiModel", "IdRefModelFkNavigation")
                        .WithMany("Trash1")
                        .HasForeignKey("IdRefModelFk")
                        .HasConstraintName("trash_id_ref_model_fk_fkey");

                    b.Navigation("IdRefCampaignFkNavigation");

                    b.Navigation("IdRefImageFkNavigation");

                    b.Navigation("IdRefModelFkNavigation");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.AiModel", b =>
                {
                    b.Navigation("Campaigns_Campaign");

                    b.Navigation("Trash1");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Campaign_Campaign", b =>
                {
                    b.Navigation("Etl_Logs");

                    b.Navigation("Image");

                    b.Navigation("TrajectoryPoints_Campaign");

                    b.Navigation("Trash1");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Country", b =>
                {
                    b.Navigation("LimitsLandSea");

                    b.Navigation("Segment");

                    b.Navigation("State");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Department", b =>
                {
                    b.Navigation("Municipality");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.ImagesForLabelling", b =>
                {
                    b.Navigation("ImagesForLabellingBoundingBoxesNavigation");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Media", b =>
                {
                    b.Navigation("Trash1");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.River_Referential", b =>
                {
                    b.Navigation("Segment");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.State", b =>
                {
                    b.Navigation("Department");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.TrajectoryPoint_Campaign", b =>
                {
                    b.Navigation("Image");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.User", b =>
                {
                    b.Navigation("Campaigns_Campaign");
                });
#pragma warning restore 612, 618
        }
    }
}
