// <auto-generated />
using System;
using Data.SchemaMigrator.Models.Raw;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.SchemaMigrator.Migrations
{
    [DbContext(typeof(RawContext))]
    partial class RawContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.SchemaMigrator.Models.Raw.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("EndLat")
                        .HasColumnType("float");

                    b.Property<double?>("EndLong")
                        .HasColumnType("float");

                    b.Property<bool>("IsAidriven")
                        .HasColumnName("IsAIDriven")
                        .HasColumnType("bit");

                    b.Property<string>("Locomotion")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Remark")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<decimal?>("RiverId")
                        .HasColumnType("numeric(8, 0)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("StartLat")
                        .HasColumnType("float");

                    b.Property<double?>("StartLong")
                        .HasColumnType("float");

                    b.Property<bool>("TracedRiverSide")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RiverId");

                    b.HasIndex("UserId");

                    b.ToTable("Campaign");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Raw.CampaignImageAssoc", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CampaignId", "ImageId")
                        .HasName("PK__Campaign__E80FE5E951C5BC76");

                    b.HasIndex("ImageId");

                    b.ToTable("CampaignImageAssoc");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Raw.CampaignStaff", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("HasBeenTrained")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<bool?>("IsStaff")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("CampaignId", "UserId")
                        .HasName("PK__Campaign__EE26065D3CBEF659");

                    b.HasIndex("UserId");

                    b.ToTable("Campaign_Staff");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Raw.Images", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("ContainerUrl")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Raw.River", b =>
                {
                    b.Property<decimal>("Cid")
                        .HasColumnName("CID")
                        .HasColumnType("numeric(8, 0)");

                    b.Property<string>("Candidat")
                        .HasColumnType("varchar(18)")
                        .HasMaxLength(18)
                        .IsUnicode(false);

                    b.Property<int>("Classe")
                        .HasColumnType("int");

                    b.Property<string>("CodeEntite")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasMaxLength(8)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .HasColumnType("varchar(86)")
                        .HasMaxLength(86)
                        .IsUnicode(false);

                    b.HasKey("Cid")
                        .HasName("PK__River__C1F8DC59ACD56E3A");

                    b.ToTable("River");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Raw.Trash", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AiVersion")
                        .HasColumnName("AI_Version")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("Aiversion1")
                        .HasColumnName("AIVersion")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("BrandType")
                        .HasColumnName("Brand_Type")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<double?>("Precision")
                        .HasColumnType("float");

                    b.Property<Guid?>("RelatedImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrashTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("RelatedImageId");

                    b.HasIndex("TrashTypeId");

                    b.ToTable("Trash");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Raw.TrashType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Trash_Type");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Raw.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<bool?>("EmailConfirmed")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Experience")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Firstname")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Lastname")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<DateTime?>("YearOfBirth")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Raw.Campaign", b =>
                {
                    b.HasOne("Data.SchemaMigrator.Models.Raw.River", "River")
                        .WithMany("Campaign")
                        .HasForeignKey("RiverId")
                        .HasConstraintName("FK__Campaign__RiverI__282DF8C2");

                    b.HasOne("Data.SchemaMigrator.Models.Raw.User", "User")
                        .WithMany("Campaign")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Campaign__UserId__2B0A656D");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Raw.CampaignImageAssoc", b =>
                {
                    b.HasOne("Data.SchemaMigrator.Models.Raw.Campaign", "Campaign")
                        .WithMany("CampaignImageAssoc")
                        .HasForeignKey("CampaignId")
                        .HasConstraintName("FK__CampaignI__Campa__6EF57B66")
                        .IsRequired();

                    b.HasOne("Data.SchemaMigrator.Models.Raw.Images", "Image")
                        .WithMany("CampaignImageAssoc")
                        .HasForeignKey("ImageId")
                        .HasConstraintName("FK__CampaignI__Image__6FE99F9F")
                        .IsRequired();
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Raw.CampaignStaff", b =>
                {
                    b.HasOne("Data.SchemaMigrator.Models.Raw.Campaign", "Campaign")
                        .WithMany("CampaignStaff")
                        .HasForeignKey("CampaignId")
                        .HasConstraintName("FK__Campaign___Campa__3E1D39E1")
                        .IsRequired();

                    b.HasOne("Data.SchemaMigrator.Models.Raw.User", "User")
                        .WithMany("CampaignStaff")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Campaign___UserI__3F115E1A")
                        .IsRequired();
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Raw.Trash", b =>
                {
                    b.HasOne("Data.SchemaMigrator.Models.Raw.Campaign", "Campaign")
                        .WithMany("Trash")
                        .HasForeignKey("CampaignId")
                        .HasConstraintName("FK__Trash__CampaignI__619B8048")
                        .IsRequired();

                    b.HasOne("Data.SchemaMigrator.Models.Raw.Images", "RelatedImage")
                        .WithMany("Trash")
                        .HasForeignKey("RelatedImageId")
                        .HasConstraintName("FK__Trash__RelatedIm__32AB8735");

                    b.HasOne("Data.SchemaMigrator.Models.Raw.TrashType", "TrashType")
                        .WithMany("Trash")
                        .HasForeignKey("TrashTypeId")
                        .HasConstraintName("FK__Trash__TrashType__160F4887")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
