// <auto-generated />
using System;
using Data.SchemaMigrator.Models.Bi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.SchemaMigrator.Migrations.Bi
{
    [DbContext(typeof(BiContext))]
    [Migration("20200312182800_Bi_InitialMigration")]
    partial class Bi_InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.SchemaMigrator.Models.Bi.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CampaignEndSeaDist")
                        .HasColumnType("int");

                    b.Property<int?>("CampaignStartSeaDist")
                        .HasColumnType("int");

                    b.Property<int?>("LitterDensity")
                        .HasColumnType("int");

                    b.Property<int?>("TotalAgriculturalWaste")
                        .HasColumnType("int");

                    b.Property<int?>("TotalBottles")
                        .HasColumnType("int");

                    b.Property<int?>("TotalCommonHouseholdItems")
                        .HasColumnType("int");

                    b.Property<int?>("TotalDist")
                        .HasColumnType("int");

                    b.Property<int?>("TotalDrinkingBottles")
                        .HasColumnType("int");

                    b.Property<int?>("TotalFishingAndHunting")
                        .HasColumnType("int");

                    b.Property<int?>("TotalFoodPackaging")
                        .HasColumnType("int");

                    b.Property<int?>("TotalFragments")
                        .HasColumnType("int");

                    b.Property<int?>("TotalIndustrialOrConstructionDebris")
                        .HasColumnType("int");

                    b.Property<int?>("TotalLitter")
                        .HasColumnType("int");

                    b.Property<int?>("TotalOthers")
                        .HasColumnType("int");

                    b.Property<int?>("TotalUnknow")
                        .HasColumnType("int");

                    b.Property<int?>("TotalUnknow10")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Campaign","bi");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Bi.Logs", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("ElapsedTime")
                        .HasColumnType("float");

                    b.Property<DateTime>("FinishedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InitiatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Logs","bi");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Bi.River", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("MeanDensityOfLitter")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("River","bi");
                });

            modelBuilder.Entity("Data.SchemaMigrator.Models.Bi.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("NumberOfCampaign")
                        .HasColumnType("int");

                    b.Property<int?>("TotalDist")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("User","bi");
                });
#pragma warning restore 612, 618
        }
    }
}
